import Head from 'next/head';
import { Navbar, Banner } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo2.jpg" />
      </Head>
      <div className="overflow-y-auto">
        <Navbar />
        <Banner />
      </div>
    </div>
  );
}
