import Head from 'next/head'
import {Banner} from 'components'
import {AnimateSharedLayout} from 'framer-motion'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo2.jpg" />
      </Head>
      <AnimateSharedLayout>
        <div className="">
          <Banner />
        </div>
      </AnimateSharedLayout>
    </div>
  )
}
