import Head from 'next/head'
import {Banner, OrderPoster, Price} from 'components'
import {getFooDData} from 'network/food-api/order-list'
import {
  DIET_MENU,
  DIET_QUERY,
  FOOD_MENU,
  FOOD_QUERY,
  MEAL_MENU,
  MEAL_QUERY,
} from 'network/food-api/config'

import {normalizeDataForPoster} from 'utils/utils'

export async function getStaticProps() {
  const highProtein = await getFooDData(DIET_QUERY)(DIET_MENU.HIGH_PROTEIN)
  const brunch = await getFooDData(MEAL_QUERY)(MEAL_MENU.BRUNCH)
  const juices = await getFooDData(FOOD_QUERY)(FOOD_MENU.JUICE)

  const highProteinList = normalizeDataForPoster(highProtein, {
    sliceFrom: 0,
    sliceTo: 5,
  })

  const juicesList = normalizeDataForPoster(juices, {
    sliceFrom: 0,
    sliceTo: 5,
  })

  const brunchList = normalizeDataForPoster(brunch, {
    sliceFrom: 0,
    sliceTo: 5,
  })

  return {
    props: {
      highProteinList: {...highProteinList, title: highProtein.title},
      juicesList: {...juicesList, title: highProtein.title},
      brunchList: {...brunchList, title: highProtein.title},
    },
  }
}

const Home = ({highProteinList, juicesList, brunchList}: any) => {
  return (
    <div>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo2.jpg" />
      </Head>
      <div>
        <Banner />
      </div>
    </div>
  )
}

export default Home
