import Head from 'next/head'
import {Banner, OrderPoster, Row, MapComponent, RowsContainer} from 'components'
import {getFooDData} from 'network/food-api/order-list'
import {
  DIET_MENU,
  DIET_QUERY,
  FOOD_MENU,
  FOOD_QUERY,
  MEAL_MENU,
  MEAL_QUERY,
} from 'network/food-api/config'

import {normalizeDataForPoster} from 'utils/utils'

export async function getStaticProps() {
  // const highProtein = await getFooDData(DIET_QUERY)(DIET_MENU.HIGH_PROTEIN)
  const juices = await getFooDData(FOOD_QUERY)(FOOD_MENU.JUICE)
  const brunch = await getFooDData(MEAL_QUERY)(MEAL_MENU.BRUNCH)

  // const highProteinList = normalizeDataForPoster(highProtein, {
  //   sliceFrom: 0,
  //   sliceTo: 4,
  // })

  const juicesList = normalizeDataForPoster(juices, {
    sliceFrom: 0,
    sliceTo: 4,
  })

  const brunchList = normalizeDataForPoster(brunch, {
    sliceFrom: 0,
    sliceTo: 4,
  })

  return {
    props: {
      // highProteinList: {data: [...highProteinList], title: highProtein.title},
      juicesList: {data: [...juicesList], title: juices.title},
      brunchList: {data: [...brunchList], title: brunch.title},
    },
  }
}

const Home = ({highProteinList, juicesList, brunchList}: any) => {
  return (
    <div>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo2.jpg" />
      </Head>
      <div className="mb-20">
        <Banner />
      </div>

      <RowsContainer>
        <Row title={brunchList.title}>
          <MapComponent
            Component={OrderPoster}
            data={brunchList.data}
            key={brunchList.title}
          />
        </Row>

        <Row title={juicesList.title}>
          <MapComponent
            Component={OrderPoster}
            data={juicesList.data}
            key={juicesList.title}
          />
        </Row>
      </RowsContainer>
    </div>
  )
}

export default Home
